### ISSUE TITLE
ppc64le vs ppc64el

### ISSUE THREAD

**Issue by marcosps** [arighi/virtme-ng#7]
I found some mentions of ppc64el, which seems a typo. Is it on purpose, or the intention was to write ppc64le? I found it when looking at commit 708347d8f08898bf0ea90912e44d8f5d9d541182, and then found that ARCH_MAPPING is also using ppc64el.

**Comment by arighi** [comment]
@marcosps ppc64el is the standard naming in Debian/Ubuntu, but then we have binaries such as powerpc64le-linux-gnu-gcc or qemu-system-ppc64le (in Ubuntu) that are using the other way around. I tried to stick with Debian standard naming when possible (because initially I had no plan to make this tool cross-distro), but maybe now we should start to figure out a naming convention that works across multiple distro...

**Comment by arighi** [comment]
Considering the status of ppc64el / le (is anybody using vng on ppc64?) and considering that this seems to work on Debian/Ubuntu, I'm going to close this one for now.

**Comment by marcosps** [comment]
Makes sense. One day I will try to run it again on a ppc64 machine ;) For now, I'm ok with closing it.
