### ISSUE TITLE
write access to /tmp

### ISSUE THREAD

**Issue by kuba-moo** [arighi/virtme-ng#76]
Hi! Some tests want to create files in /tmp, looks like that works fine in interactive mode (or at least we don't see any issues in the netdev runners in AWS), but when running the tests on a CentOS server in script mode I get:
```
vng -f tools/testing/selftests/config --cpus 4 -v -r . --user root -o ' -cpu Haswell' -- make -C tools/testing/selftests TARGETS=net TEST_PROGS=veth.sh TEST_GEN_PROGS="" run_tests
[...]
# timeout set to 3600
# selftests: net: veth.sh
[  337.790499][  T237] ip (237) used greatest stack depth: 24240 bytes left
# ./veth.sh: line 49: ns-OESNtF: Read-only file system
# chmod: cannot access 'ns-OESNtF': No such file or directory
```
Is this by design or can we assume that /tmp should be writable and its just a bug?

**Comment by arighi** [comment]
/tmp should always be writeable, I'll take a look at this tomorrow morning, I should be able to reproduce it locally. Thanks for reporting it!

**Comment by arighi** [comment]
Looking at the error:
```
# ./veth.sh: line 49: ns-OESNtF: Read-only file system
# chmod: cannot access 'ns-OESNtF': No such file or directory
```
It seems that veth.sh is not trying to write/chmod the file in /tmp, but in `$PWD`.

In fact, looking at the code, confirms that it's trying to create/chmod the file in the current working directory:
```
readonly STATS="$(mktemp -p /tmp ns-XXXXXX)"
readonly BASE=`basename $STATS`
...
create_ns() {
...
        echo "#kernel" > $BASE
        chmod go-rw $BASE
```

`vng` propagates the current working directory into the guest, so if you run it from `/` or from any location that is read-only for the current user in the host, it'll be read-only also in the guest, even if you are root.

Does it make sense? Is this the case?

Then there's the fact that veth.sh tries to write/chmod something in the current dir instead of `/tmp/` (that seems a bit wrong, unless there's a valid reason for it), but that's a separate issue.
